#!/usr/bin/php
<?php
use Micmia\Twig\GettextParser;
if ( file_exists( __DIR__ . '/../../autoload.php' ) ) {
	require_once __DIR__ . '/../../autoload.php';
} else {
	require_once __DIR__ . '/vendor/autoload.php';
}

$parser = new GettextParser();
$parser->handle();
